import "./globals.css";
import type { Metadata } from "next";
import { FontProvider } from './providers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <FontProvider />
        {children}
      </body>
    </html>
  );
}
